package com.xiaobailong.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CLASSES".
*/
public class ClassesDao extends AbstractDao<Classes, Long> {

    public static final String TABLENAME = "CLASSES";

    /**
     * Properties of entity Classes.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Parent = new Property(1, Long.class, "parent", false, "PARENT");
        public final static Property Path = new Property(2, String.class, "path", false, "PATH");
        public final static Property Filename = new Property(3, String.class, "filename", false, "FILENAME");
    }


    public ClassesDao(DaoConfig config) {
        super(config);
    }
    
    public ClassesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CLASSES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PARENT\" INTEGER," + // 1: parent
                "\"PATH\" TEXT," + // 2: path
                "\"FILENAME\" TEXT NOT NULL );"); // 3: filename
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CLASSES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Classes entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long parent = entity.getParent();
        if (parent != null) {
            stmt.bindLong(2, parent);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(3, path);
        }
        stmt.bindString(4, entity.getFilename());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Classes entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long parent = entity.getParent();
        if (parent != null) {
            stmt.bindLong(2, parent);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(3, path);
        }
        stmt.bindString(4, entity.getFilename());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Classes readEntity(Cursor cursor, int offset) {
        Classes entity = new Classes( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // parent
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // path
            cursor.getString(offset + 3) // filename
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Classes entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setParent(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setPath(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFilename(cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Classes entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Classes entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Classes entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
