package com.xiaobailong.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "STUDENT".
 */
@Entity
public class Student implements java.io.Serializable {
    private Long year_;

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String xuehao;

    @NotNull
    private String username;
    private long classes;
    private String mobile;
    private String ids;
    private String sex;

    @Generated
    public Student() {
    }

    public Student(Long id) {
        this.id = id;
    }

    @Generated
    public Student(Long year_, Long id, String xuehao, String username, long classes, String mobile, String ids, String sex) {
        this.year_ = year_;
        this.id = id;
        this.xuehao = xuehao;
        this.username = username;
        this.classes = classes;
        this.mobile = mobile;
        this.ids = ids;
        this.sex = sex;
    }

    public Long getYear_() {
        return year_;
    }

    public void setYear_(Long year_) {
        this.year_ = year_;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getXuehao() {
        return xuehao;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setXuehao(@NotNull String xuehao) {
        this.xuehao = xuehao;
    }

    @NotNull
    public String getUsername() {
        return username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(@NotNull String username) {
        this.username = username;
    }

    public long getClasses() {
        return classes;
    }

    public void setClasses(long classes) {
        this.classes = classes;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getIds() {
        return ids;
    }

    public void setIds(String ids) {
        this.ids = ids;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

}
